#!/bin/sh

KUNGFU_HOME_DIR=/opt/kungfu

KUNGFU_DATA_DIR=/shared/kungfu
KUNGFU_SOCKETS_DIR=$KUNGFU_DATA_DIR/socket
KUNGFU_LOGGING_DIR=$KUNGFU_DATA_DIR/log
KUNGFU_PID_DIR=$KUNGFU_DATA_DIR/pid
KUNGFU_RUNTIME_DIR=$KUNGFU_DATA_DIR/runtime
KUNGFU_JOURNAL_DIR=$KUNGFU_DATA_DIR/journal

groupadd -f --system --gid 666 bruce
useradd -p `openssl passwd -1 master` -m -d $KUNGFU_HOME_DIR --system --uid 666 -g bruce -G bruce,wheel --shell=/bin/bash bruce

cat <<EOT > $KUNGFU_HOME_DIR/.bashrc
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
EOT
chown -R bruce:bruce $KUNGFU_HOME_DIR

mkdir -p $KUNGFU_SOCKETS_DIR

mkdir -p $KUNGFU_LOGGING_DIR
mkdir -p $KUNGFU_LOGGING_DIR/supervisor
mkdir -p $KUNGFU_LOGGING_DIR/wingchun
mkdir -p $KUNGFU_LOGGING_DIR/strategy

mkdir -p $KUNGFU_PID_DIR

mkdir -p $KUNGFU_RUNTIME_DIR

mkdir -p $KUNGFU_JOURNAL_DIR
mkdir -p $KUNGFU_JOURNAL_DIR/system
mkdir -p $KUNGFU_JOURNAL_DIR/strategy
mkdir -p $KUNGFU_JOURNAL_DIR/user
mkdir -p $KUNGFU_JOURNAL_DIR/MD/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/MD/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/MD/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BINANCE

mkdir -p $KUNGFU_JOURNAL_DIR/MD/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/COINMEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCK

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITMAX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITMAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITMAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITMAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITMAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITMAX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITFINEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITMEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/HITBTC

mkdir -p $KUNGFU_JOURNAL_DIR/MD/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OCEANEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/HUOBI

mkdir -p $KUNGFU_JOURNAL_DIR/MD/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OCEANEXB

mkdir -p $KUNGFU_JOURNAL_DIR/MD/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/PROBIT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITHUMB

mkdir -p $KUNGFU_JOURNAL_DIR/MD/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/DAYBIT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/KUCOIN

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITSTAMP

chown -R bruce:bruce $KUNGFU_DATA_DIR

chmod +x /opt/kungfu/master/bin/*
ln -sf /opt/kungfu/master/bin/yjj /usr/bin/yjj
ln -sf /opt/kungfu/master/bin/wingchun /usr/bin/wingchun
ln -sf /opt/kungfu/master/bin/kungfuctl /usr/bin/kungfuctl

cat <<EOT > /usr/lib64/python2.7/site-packages/kungfu.pth
/opt/kungfu/master/lib/python2.7/site-packages
EOT

ln -sf /opt/kungfu/master/etc/systemd/user/kungfu.service /etc/systemd/system/kungfu.service

systemctl daemon-reload
systemctl start kungfu
